name: calcon
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  math_expressions: ^2.4.0
  device_preview: ^1.1.0
  sizer: ^2.0.15
  http: ^1.1.0
  decimal: ^2.3.3
  flutter_slidable: ^3.0.0
  search_choices: 2.2.5
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  lottie: ^2.6.0
  shimmer: ^3.0.0
  webview_flutter: ^3.0.2
  url_launcher: ^6.1.14
#  in_app_review: ^2.0.8
  rate_my_app: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:

    - assets/lottie/scientific_lottie.json
    - assets/lottie/rocket.json
    - assets/images/appScreenshot.png
    - assets/images/splash.png
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400