name: calculator_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  math_expressions: ^2.4.0
  device_preview: ^1.1.0
  sizer: ^2.0.15
  http: ^1.1.0
  flutter_slidable: ^3.0.0
#  dropdown_search: ^5.0.6
  search_choices: 2.2.5
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/animation_ln1mzksd.json
    - assets/lottie/animation_ln1na6wb.json
    - assets/lottie/animation_ln1pdz3d.json
    - assets/lottie/animation_ln1pro2l.json
    - assets/lottie/swipe.json
    - assets/lottie/swipeTwo.json
    - assets/images/appScreenshot.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
